language: python
dist: xenial
python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gorkarevilla
  password:
    secure: WXqssKJL8Y9jJCzebmOQosmOpSI89w0uJmnbIQI1BF4Cnt3XCx6kb186NgaHmtleDuaZ3OqpQMZAgxT5CalwuZdqXaS/Rg+HrYT7HXNzvOJCn3elYmTjgd/6txT/grlLN6df/NTfDbEkWP3LHbdWFDFlDaB2CKMGS8IRoAA4tgL4EzCiK/YbDMNQmVWL7/+g3Xk/bLFbDcC5/U4J8MtWd9Z92pnWMrRRjB9eSFXyRvD/cy7wDhJrr0vyvRaivU64T/DTvL0NHQe+0Q/KjbG9hr7z+tFFv+hyVsfuAz5RKAbc61T5GlBcfCmtB5HkGkaN6PZoLZmNJlP+Brz1iqFq8Yblvc26Gle+Wjg9WOeSlk1CHxq9Nx5E9u8K0dhkoQw78hHi6TF/3SnRIl/5qUp1fEHDG1BNnns1j0x7AGmxB1hsaquHfdaCo/6n1EV+KGS6bR7i/9gc44LfI6kA5QmPpGxDN8CbtuUE9PPpKa9P3/MgiXy+VaWnP1vnEb2Iy8SVizelQTwNj3TGwMj0a7xrNlSV/HaX5SOOQw0zordBEkI/1eV0IFqO5z1DQRQQUbIf6EnKmeYe8vCvikckx3R9yrr3agM4c8laH55UJZH0qFUgQvol3qGGoODSF4L8VhoYk5a1N11gci/h4BTBmFN/jOeUYbNOcUK4DRDOk/Ca61E=
  on:
    tags: true
    repo: Ratxi/hoodex
    python: 3.7
